name       : colord
version    : 1.0.2
release    : 12
source     :
    - http://www.freedesktop.org/software/colord/releases/colord-1.0.2.tar.xz : b99d1d07fe21a37b446aa173a35c54fd669324ad61762a7545b1624c896a8a39
license    :
    - GPL-2.0
summary    : Color Daemon
builddeps  :
    - pkgconfig(lcms2)
    - pkgconfig32(lcms2)
    - pkgconfig(sqlite3)
    - pkgconfig32(sqlite3)
    - pkgconfig(gusb)
    - pkgconfig32(gusb)
    - pkgconfig32(liblzma)
    - pkgconfig(gtk-doc)
    - libgcc-32bit
    - glibc-32bit-devel
    - dbus-32bit-devel
    - dbus-32bit
    - libgcrypt-32bit-devel
emul32     : yes
description: |
    colord is a system service that makes it easy to manage, install and generate color profiles to accurately color manage input and output devices.
setup      : |
    %patch -p1 < $pkgfiles/0001-Support-a-stateless-configuration.patch
    ./autogen.sh
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        exOpts="--disable-polkit"
    else
        exOpts="--enable-polkit"
    fi
    %configure --disable-static \
               --prefix=/usr \
               --with-udevrulesdir=%libdir%/udev/rules.d \
               --with-daemon-user=colord \
               $exOpts
build      : |
    %make
install    : |
    %make_install
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        # Remove derps.
        rm -rf $installdir/%libdir%/colord{,-plugins,-sensors}
        rm -rf $installdir/%libdir%/udev
    fi
    rm -rf $installdir/var
    install -D -m 00644 $pkgfiles/colord.sysusers $installdir/%libdir%/sysusers.d/colord.conf
