name       : colord
version    : 1.3.5
release    : 18
source     :
    - https://www.freedesktop.org/software/colord/releases/colord-1.3.5.tar.xz : 2daa8ffd2a532d7094927cd1a4af595b8310cea66f7707edcf6ab743460feed2
license    : GPL-2.0
component  : desktop.core
summary    : Color Daemon
description: |
    colord is a system service that makes it easy to manage, install and generate color profiles to accurately color manage input and output devices.
builddeps  :
    - pkgconfig32(dbus-1)
    - pkgconfig32(glib-2.0)
    - pkgconfig32(gudev-1.0)
    - pkgconfig32(gusb)
    - pkgconfig32(lcms2)
    - pkgconfig32(libusb-1.0)
    - pkgconfig32(liblzma)
    - pkgconfig32(sqlite3)
    - pkgconfig(gtk-doc)
    - libgcrypt-32bit-devel
    - vala
emul32     : yes
setup      : |
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        exOpts="--disable-polkit"
    else
        exOpts="--enable-polkit --enable-vala"
    fi
    %configure --disable-static \
               --prefix=/usr \
               --with-udevrulesdir=%libdir%/udev/rules.d \
               --with-daemon-user=colord \
               --disable-argyllcms-sensor \
               $exOpts
build      : |
    %make
install    : |
    %make_install
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        # Remove derps.
        rm -rf $installdir/%libdir%/colord{,-plugins,-sensors}
        rm -rf $installdir/%libdir%/udev
    else
        install -D -m 00644 $pkgfiles/colord.sysusers $installdir/%libdir%/sysusers.d/colord.conf
    fi
    rm -rf $installdir/var
