name       : colord
version    : 1.4.6
release    : 20
source     :
    - https://www.freedesktop.org/software/colord/releases/colord-1.4.6.tar.xz : 7407631a27bfe5d1b672e7ae42777001c105d860b7b7392283c8c6300de88e6f
license    : GPL-2.0-or-later
component  : desktop.core
summary    : Color Daemon
description: |
    colord is a system service that makes it easy to manage, install and generate color profiles to accurately color manage input and output devices.
builddeps  :
    - pkgconfig32(dbus-1)
    - pkgconfig32(glib-2.0)
    - pkgconfig32(gudev-1.0)
    - pkgconfig32(gusb)
    - pkgconfig32(lcms2)
    - pkgconfig32(libusb-1.0)
    - pkgconfig32(liblzma)
    - pkgconfig32(libsystemd)
    - pkgconfig32(sqlite3)
    - pkgconfig(gtk-doc)
    - libgcrypt-32bit-devel
    - vala
emul32     : yes
setup      : |
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        exOpts="-Ddaemon=false -Dvapi=false -Dintrospection=false"
    else
        exOpts="-Ddaemon=true -Dvapi=true -Dintrospection=true"
    fi
    %meson_configure \
        -Dargyllcms_sensor=false \
        -Ddaemon_user=colord \
        -Ddocs=false \
        $exOpts
build      : |
    %ninja_build
install    : |
    %ninja_install
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        # Remove derps.
        rm -rf $installdir/%libdir%/colord{,-plugins,-sensors}
        rm -rf $installdir/%libdir%/udev
    else
        install -D -m 00644 $pkgfiles/colord.sysusers $installdir/%libdir%/sysusers.d/colord.conf
    fi
    rm -rf $installdir/var
