name       : colord
version    : 1.4.5
release    : 19
source     :
    - https://www.freedesktop.org/software/colord/releases/colord-1.4.5.tar.xz : b774ea443d239f4a2ee1853bd678426e669ddeda413dcb71cea1638c4d6c5e17
license    : GPL-2.0-or-later
component  : desktop.core
summary    : Color Daemon
description: |
    colord is a system service that makes it easy to manage, install and generate color profiles to accurately color manage input and output devices.
builddeps  :
    - pkgconfig32(dbus-1)
    - pkgconfig32(glib-2.0)
    - pkgconfig32(gudev-1.0)
    - pkgconfig32(gusb)
    - pkgconfig32(lcms2)
    - pkgconfig32(libusb-1.0)
    - pkgconfig32(liblzma)
    - pkgconfig32(libsystemd)
    - pkgconfig32(sqlite3)
    - pkgconfig(gtk-doc)
    - libgcrypt-32bit-devel
    - vala
emul32     : yes
setup      : |
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        %patch -p1 < $pkgfiles/0001-Don-t-force-build-gir.patch
        exOpts="-Ddaemon=false -Dvapi=false"
    else
        exOpts="-Ddaemon=true -Dvapi=true"
    fi
    %meson_configure \
        -Dargyllcms_sensor=false \
        -Ddaemon_user=colord \
        -Ddocs=false \
        -Dudevrulesdir=%libdir%/udev/rules.d \
        $exOpts
build      : |
    %ninja_build
install    : |
    %ninja_install
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        # Remove derps.
        rm -rf $installdir/%libdir%/colord{,-plugins,-sensors}
        rm -rf $installdir/%libdir%/udev
    else
        install -D -m 00644 $pkgfiles/colord.sysusers $installdir/%libdir%/sysusers.d/colord.conf
    fi
    rm -rf $installdir/var
