name        : colord
version     : 1.0.2
release     : 8
source      :
    - http://www.freedesktop.org/software/colord/releases/colord-1.0.2.tar.xz : b99d1d07fe21a37b446aa173a35c54fd669324ad61762a7545b1624c896a8a39
license     :
    - GPL-2.0
summary     : Color Daemon
builddeps   :
    - pkgconfig(lcms2)
    - pkgconfig(sqlite3)
    - pkgconfig(gusb)
    - pkgconfig(gtk-doc)
description : |
    colord is a system service that makes it easy to manage, install and generate color profiles to accurately color manage input and output devices.
setup      : |
    %patch -p1 < $pkgfiles/0001-Support-a-stateless-configuration.patch
    ./autogen.sh
    %configure --disable-static \
               --with-udevrulesdir=%libdir%/udev/rules.d
build      : |
    %make
install    : |
    %make_install
